apiVersion: apps/v1
kind: Deployment
metadata:
  name: wodch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wodch
  template:
    metadata:
      labels:
        app: wodch
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/gerrited/wodch:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wodch
spec:
  selector:
    app: wodch
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wodch
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: wodch.g11s.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wodch
                port:
                  number: 80
